// ข้อมูลหลักของเว็บไซต์ — เปลี่ยนค่าตรงนี้เพื่ออัปเดตทั้งเว็บ
export const siteConfig = {
  name: "อนุชา วังราช",
  nameEn: "Anucha Wangrat",
  role: "Full-Stack Developer",
  roleTh: "นักพัฒนาเว็บและซอฟต์แวร์",
  tagline: "สร้างเว็บแอพ เว็บธุรกิจ แอพมือถือ ระบบ POS และระบบตามสั่ง",
  description:
    "อนุชา วังราช — Full-Stack Developer รับทำเว็บแอพ เว็บไซต์ธุรกิจ แอพมือถือ ระบบ POS และระบบตามสั่ง พร้อมให้คำปรึกษาและดูแลหลังการขาย",
  url: "https://dgkingshop.com",
  email: "anucha.wangrat@outlook.com",
  phone: "0612373304",
  phoneDisplay: "061-237-3304",
  lineId: "anucha1997w",
  facebook: "https://facebook.com/Developer22",
  facebookPage: "https://facebook.com/AWDev22",
  github: "https://github.com/anucha010340w-coder",
  keywords: [
    "รับทำเว็บไซต์",
    "รับทำเว็บ",
    "รับทำเว็บไซต์ ราคา",
    "รับทำเว็บ Next.js",
    "รับทำเว็บ React",
    "รับทำเว็บธุรกิจ",
    "รับทำเว็บบริษัท",
    "รับทำเว็บขายของ",
    "รับทำเว็บแอพ",
    "รับทำเว็บ ส่งงานเร็ว",
    "รับทำเว็บ ราคาประหยัด",
    "รับทำเว็บ ใกล้ฉัน",
    "รับทำแอพ",
    "รับทำแอพมือถือ",
    "รับทำแอพ iOS Android",
    "รับทำแอพ React Native",
    "รับทำแอพ Flutter",
    "รับทำระบบ",
    "รับทำระบบตามสั่ง",
    "รับทำระบบ POS",
    "รับทำระบบ POS ร้านอาหาร",
    "รับทำระบบจองคิว",
    "รับทำระบบคลังสินค้า",
    "รับทำระบบจัดการ",
    "รับทำร้านค้าออนไลน์",
    "รับทำระบบ CRM",
    "รับทำระบบ ERP",
    "รับเขียนโปรแกรม",
    "รับเขียนโปรแกรม ระบบตามสั่ง",
    "รับทำเว็บไซต์ SEO",
    "รับทำเว็บ ติดอันดับ Google",
    "ที่ปรึกษา IT",
    "ที่ปรึกษาระบบสารสนเทศ",
    "Full-Stack Developer",
    "นักพัฒนาเว็บ",
    "นักพัฒนาเว็บ รับทำ",
    "Web Developer Thailand",
    "Next.js Developer",
    "React Developer",
    "TypeScript Developer",
    "POS System",
    "Anucha Wangrat",
    "อนุชา วังราช",
    "อนุชา วังราช Developer",
    "อนุชา วังราช รับทำเว็บ",
    "AW Dev",
    "dgkingshop",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
