// ข้อมูลหลักของเว็บไซต์ — เปลี่ยนค่าตรงนี้เพื่ออัปเดตทั้งเว็บ
export const siteConfig = {
  name: "อนุชา วังราช",
  nameEn: "Anucha Wangrat",
  role: "Full-Stack Developer",
  roleTh: "นักพัฒนาเว็บและซอฟต์แวร์",
  tagline: "สร้างเว็บแอพ เว็บธุรกิจ แอพมือถือ ระบบ POS และระบบตามสั่ง",
  description:
    "อนุชา วังราช — Full-Stack Developer รับทำเว็บแอพ เว็บไซต์ธุรกิจ แอพมือถือ ระบบ POS และระบบตามสั่ง พร้อมให้คำปรึกษาและดูแลหลังการขาย",
  url: "https://dgkingshop.com",
  email: "anucha.wangrat@outlook.com",
  phone: "0612373304",
  phoneDisplay: "061-237-3304",
  lineId: "anucha1997w",
  facebook: "https://facebook.com/Developer22",
  facebookPage: "https://facebook.com/AWDev22",
  github: "https://github.com/anucha010340w-coder",
  keywords: [
    "รับทำเว็บไซต์",
    "รับเขียนโปรแกรม",
    "Full-Stack Developer",
    "นักพัฒนาเว็บ",
    "ระบบ POS",
    "เว็บแอพ",
    "แอพมือถือ",
    "Anucha Wangrat",
    "อนุชา วังราช",
    "รับทำเว็บธุรกิจ",
    "รับทำเว็บ",
    "รับทำแอพ",
    "ระบบตามสั่ง",
    "รับทำระบบ",
    "POS System",
    "Web Developer Thailand",
    "Next.js Developer",
    "React Developer",
    "อนุชา วังราช Developer",
    "AW Dev",
    "dgkingshop",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
